run:
  timeout: 5m
  skip-files:
    - '.*_test.go'
    - '.*_mock.go'
    - "vendor/*"

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - exhaustruct
    - gci # конфликтует с другими линтерами
    - gomnd # todo по возможности избавиться от магических чисел, но он ругается вообще на все подряд
    - musttag # todo падает

linters-settings:
  varnamelen:
    ignore-names:
      - id
  tagliatelle:
    case:
      rules:
        json: snake
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - ab_script
          - github.com